apiVersion: bricksv1
kind: Deployment
metadata:
  name: nayax-dev-networking
spec:
  blueprint: networking_stack
  version: 1.0.4
  collection: andrii-test-1-1
  force: false
  planOnly: false
  props:
    vpc_name: nayax-dev-vpc
    cidr: "10.0.0.0/16"
    azs:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    private_subnets:
      - "10.0.1.0/24"
      - "10.0.2.0/24"
      - "10.0.3.0/24"
    public_subnets:
      - "10.0.101.0/24"
      - "10.0.102.0/24"
      - "10.0.103.0/24"
    enable_nat_gateway: true
    single_nat_gateway: false
    environment: dev
    region: us-east-1
